# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:11.14.0

    working_directory: ~/semaphore/semaphorejs

    steps:
      - checkout:
          path: ~/semaphore

      # restore or install npm packages
      - restore_cache:
          name: restore-npm-cache
          keys:
            - v1.10-dependencies-{{ checksum "package-lock.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1.10-dependencies-{{ checksum "package-lock.json" }}

      # checksum the snarks definitions
      - run:
          name: checksum-snarks
          command: cd scripts && ./checksum_snarks.sh

      # Download and cache dependencies
      - restore_cache:
          name: restore-snark-cache
          keys:
            - v1.11-dependencies-{{ checksum "build/.snark_checksum" }}

      # build snarks
      - run:
          name: end-to-end
          command: cd scripts && ./build_snarks.sh
          no_output_timeout: 600m

      # cache generated snark circuit and keys
      - save_cache:
          key: v1.11-dependencies-{{ checksum "build/.snark_checksum" }}
          paths:
            - build/circuit.json
            - build/proving_key.bin
            - build/proving_key.json
            - build/verification_key.json
            - build/verifier.sol

      # build snarks
      - run:
          name: integration_tests
          command: cd scripts && ./integration_tests.sh
          no_output_timeout: 600m

      - store_artifacts:
          path: ~/semaphore/semaphorejs/build

