# I got this by calling derivePublicKey from zk-kit on the integer 123, 
# just as semaphore does before inputting the data into the circuit
secret = "0x999bc5d5764df4bf04cde322569a3b65e991668b8e00aa25487b34251588bff"
hash_path = [
      '5',
      '5558359459771725727593826278265342308584225092343962757289948761260561575479',
      '3720616653028013822312861221679392249031832781774563366107458835261883914924',
      '12149159335560625006476125566762465580257337488628181926934192232419917268760',
      '16',
      '0',
      '0',
      '0',
      '0',
      '0'
    ]
indices = 128
root = "0x27a22b81d6259155fd89206a7535cc17c6bc9ab78e054da9a244805cc9fe758d"
# siblings= [
#     '0x290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e5',
#     '0x38682aa1cb5ae4e0a3f13da432a95c77c5c111f6f030faf9cad641ce1ed7383',
#     '0x2cf028e1d34324e13225fab149060764729ef544559a37e84d1811f564317ae3',
#     '0x2825bc469c3f1c335a323eb98a91d07f4600cdcc8745038a19277d4775da2a99',
#     '0x23ae6a688a4609836c0942dcf3bd96d3e6032d62a3e5abda4074ff7c3f52f07b',
#     '0x77ebc88dd933f28462a20502bcf67badacab0e40e0c9895272d08deba1f48f3',
#     '0xa19b89829193b299d585a982c02a4efc0143e5bb2d5f83bad4ac2f36a074abc',
#     '0x5526ae1b8a7bfff5a8f0ce88633005a31b48b622224bb04031844721a413e21',
#     '0xc644c18f0199297d57c03e75a8287f20b8fb5e9829faf8106251ca71184f5e4',
#     '0x15272e3f81789a1f46d3ee2c6d456a6550094ea225772004554e9a39b8dced92',
#     '0x70065048441e7c403ee82f4e8ee63bf8b2bb312e92c1b80c87fe9e9b4c1b809',
#     '0x180ed494277be1500aa7ad7bba08f54ac0c5f4519ed1b3d1d06fa1473dd90007',
#     '0x2575babfcc92d2aec9a77c90b4fb7ae667465ad4d901ac1fbdfbf41d5ec6d1e9',
#     '0x11b974da6ed4be6ac6577005433331555653420b1bda1799e512ef840c06ee6f',
#     '0x8536ba04d288460fd01ca5629d299716cef016a4addbbb6b8c91c3c4c9e273e',
#     '0x2da0705d417c55fca190adab667b861538a025a71ec37921b85aa20819f62c58'
# ]
# index = "0x0000000000000000000000000000000000000000000000000000000000004000"
# nullifier_hash= '0x19f6c84d6694188967194ebceea728b6d5c05adbed0a71ea21004ecd0aae9cfb'
# root= '0x229f25e27de5c213dd2f64c221670d886d85b568cb9def381f409d4a64ad7e09'
# pubkey_x = "0x1fe9cbc6b7906cf8dc5ae8e12aa2cdbd6301d5356d95a50963de71518fd7b901"
# pubkey_y = "0x27edbd40d949dba6b518c79ca4e88768c93bde75dd8e02cd47b954b69e1b0849"
